coverage:
  range: 90..100
  round: down
  precision: 2
  status:
    project:
      default:
        threshold: 1%
ignore:
  - "examples"
  - "tests"
# Make less noisy comments
comment:
  layout: "files"
  require_changes: yes
